pipeline {

    agent any

    tools {
        maven 'Maven'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Compile') {
            steps {
                sh 'cd vehicle-parking && mvn clean compile'
            }
        }

        stage('Test') {
            steps {
                sh 'cd vehicle-parking && mvn test'
            }
        }

        stage('Package') {
            steps {
                sh 'cd vehicle-parking && mvn package'
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'vehicle-parking/target/*.jar'
            }
        }
    }

    post {
        always {
            junit allowEmptyResults: true, testResults: 'vehicle-parking/target/surefire-reports/*.xml'
        }
    }
}
